### ISSUE TITLE
Add barman-rsync cron job

### ISSUE THREAD

**Issue by rafecolton** [modcloth/ansible-role-modcloth-barman#4]
...for syncing `barman_home` to a remote location (i.e. NFS)

**Comment by udinir-zz** [comment]
What are we using NFS for and why NFS which in general is a bad dependency to add to servers IMO.

**Comment by rafecolton** [comment]
The plan is to have a cron job (disabled by default) that syncs the entire barman home directory somewhere off the machine so we can still restore from a backup if the backup server explodes.  Optionally, we could push it to s3
